### PR TITLE
Pull Request as promised on Discord

### PR DESCRIPTION
**Pull request by ReDBaroN1**

### CODE REVIEW

**Comment by ReDBaroN1** [comment]
Addded the fix for vehicle weapon and magazine restrictions

**Review by Ghostrider-DbD- — APPROVED** [review]

**Review by Ghostrider-DbD- — APPROVED** [review]

**Review by Ghostrider-DbD- — APPROVED** [review]

**Review by Ghostrider-DbD- — CHANGES_REQUESTED** [review]
Thank you for catching this. 

would you mind removing the #include for the defines?
They are already included in

**Review by Ghostrider-DbD- — CHANGES_REQUESTED** [review]
Thank you for catching this. 

would you mind removing the #include for the defines?
They are already included in addons\VGFE\VGFEdialogs.hpp (look within the class definitions for controls, the include is at the top of that section. This way, the class definitions referenced are local to that dialog :).

**Review by Ghostrider-DbD- — COMMENTED** [review]
Where do you think this information should go? would it be better under epoch_config\configs\CfgRemoteExec.hpp? with a comment to merge with that file?

**Review by Ghostrider-DbD- — APPROVED** [review]
Looks good, thanks for tidying that bit up.

**Review by Ghostrider-DbD- — CHANGES_REQUESTED** [review]
good catch, Thank you!

When you get a chance, would you mind removing 	
class VGFE_fnc_client_sendVGFERequest
		{
			allowedTargets = 2;
			jip = 0;
		};

That is local to the client and does not need to be defined here.

**Review by Ghostrider-DbD- — COMMENTED** [review]
I am waiting to see what He-man suggests. He was leaning toward calling the exisiting Epoch server functions, which would solve some issues you noticed. I would then want to add a bit of additional code that set the vehicle locks, nicknames (which are super handy if you have a VG) and any other parameters that need adjusting. I'd be curious about your thoughts about nicknames. The Epoch system only applies them to certain vehicles defined in the code. Should I suggest a modification to the loadVehicles function to either adds a config or broadens the application of custom license plates?

**Comment by ReDBaroN1** [comment]
> Thank you for catching this.
> 
> would you mind removing the #include for the defines?
> They are already included in addons\VGFE\VGFEdialogs.hpp (look within the class definitions for controls, the include is at the top of that section. This way, the class definitions referenced are local to that dialog :).

Oops, didn't spot that apologies. Search fail :D 
Updated the pull request

**Comment by ReDBaroN1** [comment]
> good catch, Thank you!
> 
> When you get a chance, would you mind removing
> class VGFE_fnc_client_sendVGFERequest
> {
> allowedTargets = 2;
> jip = 0;
> };
> 
> That is local to the client and does not need to be defined here.

Done and updated in the pull request

**Comment by ReDBaroN1** [comment]
> Where do you think this information should go? would it be better under epoch_config\configs\CfgRemoteExec.hpp? with a comment to merge with that file?

Yes, You had one in there too which is why I deleted the one on the other location which was a duplicate.
I think it's good in that location with instructions to merge.

**Comment by ReDBaroN1** [comment]
> I am waiting to see what He-man suggests. He was leaning toward calling the exisiting Epoch server functions, which would solve some issues you noticed. I would then want to add a bit of additional code that set the vehicle locks, nicknames (which are super handy if you have a VG) and any other parameters that need adjusting. I'd be curious about your thoughts about nicknames. The Epoch system only applies them to certain vehicles defined in the code. Should I suggest a modification to the loadVehicles function to either adds a config or broadens the application of custom license plates?

I like the point about using epoch's vehicle spawning code and to be honest it's that I've been looking at while trying to fix the rearming and repairing issues. But, no success yet.

On the nicks, I do think they're good but, maybe duplicitous with the new number plate system from epoch you mention. I know in exile when players were first forced to enter nicks a lot of requests came in to know how to switch it off. Do you know where the code is for the epoch nicks? I would like to look at that and see if it can be done for the custom vehicles most servers will have added.

**Review by Ghostrider-DbD- — APPROVED** [review]

**Pull request closed without merging**
